INSERT INTO COMPOSE VALUES('Julien', 1, 'Riven', 'Top');
INSERT INTO COMPOSE VALUES('Grig1', 2, 'Janna', 'Support');
INSERT INTO COMPOSE VALUES('TSM Zven', 3, 'Fiora', 'Top');
INSERT INTO COMPOSE VALUES('L 5 22 9', 4, 'Irelia', 'Top');
INSERT INTO COMPOSE VALUES('Neøø', 5, 'Ahri', 'Mid');
INSERT INTO COMPOSE VALUES('Macotoˉ', 6, 'Akali', 'Jungle');
INSERT INTO COMPOSE VALUES('Winter', 7, 'Ashe', 'Adc');
INSERT INTO COMPOSE VALUES('Desired Game', 8, 'Jinx', 'Adc');
INSERT INTO COMPOSE VALUES('Liquid Impact', 9, 'Karma', 'Support');
INSERT INTO COMPOSE VALUES('HotGuy6Pack', 10, 'Katarina', 'Mid');